import StoreProvider from '@/app/StoreProvider';
import { Header } from '@/components/Header';
import { SideBars } from '@/components/SideBar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      className="flex"
      style={{
        height: '100%',
        overflow: 'hidden',
      }}>
      <StoreProvider>
        <SideBars />
        <div className="flex-1">
          <Header />
          <Suspense>{children}</Suspense>
        </div>
      </StoreProvider>
    </main>
  );
}
