import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from './components/Header';
import { SideBars } from './components/SideBar';
import StoreProvider from '../StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="flex"
          style={{
            height: '100%',
            overflow: 'hidden',
          }}>
          <StoreProvider>
            <SideBars />
            <div className="flex-1">
              <Header />
              {children}
            </div>
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
